spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8181/realms/master
  data:
    redis:
      host: localhost
      port: 6379
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: route1
              uri: http://localhost:8000
              predicates:
                - Path=/api/first/**
              filters:
                - StripPrefix=2
                - PrefixPath=/api/dna
                - name: RequestRateLimiter
                  args:
                    redis-rate-limiter.replenishRate: 1
                    redis-rate-limiter.burstCapacity: 5
                    redis-rate-limiter.requestedTokens: 1
                    key-resolver: "#{@userKeyResolver}"

                - name: CircuitBreaker
                  args:
                    name: httpCircuitBreaker
                    fallbackUri: forward:/fallback


            - id: route2
              uri: http://localhost:9000/
              predicates:
                - Path=/api/second/**
              filters:
                - StripPrefix=2
                - name: RequestRateLimiter
                  args:
                    redis-rate-limiter.replenishRate: 1
                    redis-rate-limiter.burstCapacity: 5
                    redis-rate-limiter.requestedTokens: 1
                    key-resolver: "#{@userKeyResolver}"

                - name: CircuitBreaker
                  args:
                    name: httpCircuitBreaker
                    fallbackUri: forward:/fallback

            - id: route3
              uri: http://localhost:9000
              predicates:
                - Path=/api/admin/**
              filters:
                - StripPrefix=2
                - PrefixPath=/get
                - name: RequestRateLimiter
                  args:
                    redis-rate-limiter.replenishRate: 1
                    redis-rate-limiter.burstCapacity: 5
                    redis-rate-limiter.requestedTokens: 1
                    key-resolver: "#{@userKeyResolver}"

                - name: CircuitBreaker
                  args:
                    name: httpCircuitBreaker
                    fallbackUri: forward:/fallback

management:
  endpoints:
    web:
      exposure:
        include: health , gateway , metrics , env

    access:
      default: unrestricted

  endpoint:
    health:
      show-details: always
  tracing:
    sampling:
      probability: 1

  otlp:
    tracing:
      endpoint: http://localhost:4318


resilience4j:
  circuitbreaker:
    instances:
      httpCircuitBreaker:
        sliding-window-size: 10
        failure-rate-threshold: 50
        wait-duration-in-open-state: 10s
        permitted-number-of-calls-in-half-open-state: 3

  timelimiter:
    instances:
      httpCircuitBreaker:
        timeout-duration: 5s
